# Site settings
title:          生命在于折腾
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://tim-gao.github.io"

# Author
author:
name:         Tim Gao
url:          http://julysxy.xyz
email:        timgao720@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

include: [_pages]

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
google-plus: 116481721016030562247
github: tim-gao
weixin:
weibo: 1800010472